displayName=Battle-Mage Mode
author=ConeCone
description= Challenge yourself: Align to a god faction, play by the Battle-Mage rules.
tags=challenge,ironman,magic,restriction,pkp,battle-mage,pvm,hardcore
plugins=com.battlemage.BattleMagePlugin
build=standard
